name: Issue Form
description: Use this form to report an issue
labels: ["needs-triage"]
body:
  - type: dropdown
    id: issue-type
    attributes:
      label: What is this issue related to?
      description: Please select the type of issue you're reporting.
      options:
        - Feature
        - Bug
        - Performance
        - Documentation
        - Enhancement
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please enter an explicit description of your issue.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what should happen when this issue is resolved.

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: Explain what currently happens when this issue is encountered.

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information (optional)
      description: Please add any additional context, logs, or details that might be helpful in addressing the issue here.

  - type: checkboxes
    id : confirmation-checklist
    attributes :
       label : Confirmation Checklist
       options :
         - label : I have searched for similar issues before creating this one.
         - label : I have provided all the necessary information to understand and reproduce the issue.
